background = #333333
foreground = #b1b1b1

cursor-color = #bdacb0
cursor-text = #333333

selection-background = #484848
selection-foreground = #b1b1b1

# Black
palette = 0=#585858
# Dark Red
palette = 1=#808080
# Dark Green
palette = 2=#747474
# Dark Yellow
palette = 3=#bdacb0
# Dark Blue
palette = 4=#696969
# Dark Magenta
palette = 5=#747474
# Dark Cyan
palette = 6=#808080
# Light Gray
palette = 7=#808080

# Gray
palette = 8=#585858
# Red
palette = 9=#808080
# Green
palette = 10=#747474
# Yellow
palette = 11=#bdacb0
# Blue
palette = 12=#696969
# Magenta
palette = 13=#747474
# Cyan
palette = 14=#808080
# White
palette = 15=#808080
