background = #f5f9fb
foreground = #242a2c

selection-background = #e8eced
selection-foreground = #242a2c

# Black
palette = 0=#474e51
# Dark Red
palette = 1=#9ea6a9
# Dark Green
palette = 2=#868e90
# Dark Yellow
palette = 3=#0795fd
# Dark Blue
palette = 4=#9ea6a9
# Dark Magenta
palette = 5=#868e90
# Dark Cyan
palette = 6=#9ea6a9
# Light Gray
palette = 7=#9ea6a9

# Gray
palette = 8=#585f61
# Red
palette = 9=#9ea6a9
# Green
palette = 10=#868e90
# Yellow
palette = 11=#fc8e06
# Blue
palette = 12=#9ea6a9
# Magenta
palette = 13=#868e90
# Cyan
palette = 14=#9ea6a9
# White
palette = 15=#9ea6a9
