background = #fef2e1
foreground = #3a2e3b

selection-background = #f8e7d0
selection-foreground = #3a2e3b

# Black
palette = 0=#634c64
# Dark Red
palette = 1=#c65e53
# Dark Green
palette = 2=#428a68
# Dark Yellow
palette = 3=#de8641
# Dark Blue
palette = 4=#aa6f83
# Dark Magenta
palette = 5=#ec935f
# Dark Cyan
palette = 6=#529e86
# Light Gray
palette = 7=#d1ba9b

# Gray
palette = 8=#725a73
# Red
palette = 9=#db7070
# Green
palette = 10=#52ad82
# Yellow
palette = 11=#ea9d34
# Blue
palette = 12=#9175a3
# Magenta
palette = 13=#f0a274
# Cyan
palette = 14=#6aaf9a
# White
palette = 15=#f2daba
