background = #eef0f2
foreground = #313334

selection-background = #dcdee0
selection-foreground = #313334

# Black
palette = 0=#313334
# Dark Red
palette = 1=#6d7d88
# Dark Green
palette = 2=#9dadb9
# Dark Yellow
palette = 3=#8595a0
# Dark Blue
palette = 4=#6d7d88
# Dark Magenta
palette = 5=#2f8728
# Dark Cyan
palette = 6=#50a648
# Light Gray
palette = 7=#9dadb9

# Gray
palette = 8=#5c6b76
# Red
palette = 9=#6d7d88
# Green
palette = 10=#9dadb9
# Yellow
palette = 11=#8595a0
# Blue
palette = 12=#6d7d88
# Magenta
palette = 13=#2f8728
# Cyan
palette = 14=#50a648
# White
palette = 15=#dcdee0
