background = #e6fbf2
foreground = #172822

selection-background = #d5eae2
selection-foreground = #172822

# Black
palette = 0=#172822
# Dark Red
palette = 1=#61746c
# Dark Green
palette = 2=#849790
# Dark Yellow
palette = 3=#72857e
# Dark Blue
palette = 4=#61746c
# Dark Magenta
palette = 5=#5981e0
# Dark Cyan
palette = 6=#00a292
# Light Gray
palette = 7=#849790

# Gray
palette = 8=#50625b
# Red
palette = 9=#61746c
# Green
palette = 10=#849790
# Yellow
palette = 11=#72857e
# Blue
palette = 12=#61746c
# Magenta
palette = 13=#8d85ed
# Cyan
palette = 14=#00b290
# White
palette = 15=#d5eae2
