background = #172822
foreground = #dcf1e9

selection-background = #354740
selection-foreground = #dcf1e9

# Black
palette = 0=#354740
# Dark Red
palette = 1=#849790
# Dark Green
palette = 2=#849790
# Dark Yellow
palette = 3=#72857e
# Dark Blue
palette = 4=#61746c
# Dark Magenta
palette = 5=#709afb
# Dark Cyan
palette = 6=#00b9a9
# Light Gray
palette = 7=#d2e7df

# Gray
palette = 8=#61746c
# Red
palette = 9=#849790
# Green
palette = 10=#849790
# Yellow
palette = 11=#72857e
# Blue
palette = 12=#61746c
# Magenta
palette = 13=#a59eff
# Cyan
palette = 14=#25c9a9
# White
palette = 15=#dcf1e9
