background = #d5e2dc
foreground = #1d2722

selection-background = #bbc8c2
selection-foreground = #1d2722

# Black
palette = 0=#1d2722
# Dark Red
palette = 1=#66726d
# Dark Green
palette = 2=#899590
# Dark Yellow
palette = 3=#78837e
# Dark Blue
palette = 4=#66726d
# Dark Magenta
palette = 5=#5981e0
# Dark Cyan
palette = 6=#0fa05c
# Light Gray
palette = 7=#899590

# Gray
palette = 8=#55615c
# Red
palette = 9=#66726d
# Green
palette = 10=#899590
# Yellow
palette = 11=#78837e
# Blue
palette = 12=#66726d
# Magenta
palette = 13=#8d85ed
# Cyan
palette = 14=#00b290
# White
palette = 15=#bbc8c2
